<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yuzgdeMacBook-Pro.local" failures="1" tests="2" name="com.yiibai4.TestTimeout" time="5.026" errors="0" timestamp="17 Oct 2020 07:00:15 GMT">
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldPass" time="4.010"/>
  <testcase classname="com.yiibai4.TestTimeout" name="testThisShouldFail" time="1.016">
    <failure message="Method org.testng.internal.TestNGMethod.testThisShouldFail() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testThisShouldFail() didn't finish within the time-out 1000
	at java.base@14.0.2/java.lang.Object.clone(Native Method)
	at java.base@14.0.2/java.lang.invoke.MethodTypeForm.canonicalizeAll(MethodTypeForm.java:318)
	at java.base@14.0.2/java.lang.invoke.MethodTypeForm.canonicalize(MethodTypeForm.java:243)
	at java.base@14.0.2/java.lang.invoke.MethodTypeForm.findForm(MethodTypeForm.java:215)
	at java.base@14.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:327)
	at java.base@14.0.2/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:377)
	at java.base@14.0.2/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
	at java.base@14.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@14.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base@14.0.2/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testThisShouldFail -->
</testsuite> <!-- com.yiibai4.TestTimeout -->
